<div class="row section section-1 active">
    <div class="row">
        <h2 class="title">Touch Display with 3 programmable doses</h2>
        <p class="subtitle">"Extra Dose" mode and maintenance alerts</p>
    </div>
    <div class="row">
        <h2 class="title">New ELR System</h2>
        <p class="subtitle">With the sloped grinding chamber providing extremely low retention.</p>
    </div>
    <div class="row">
        <h2 class="title">Automatic filter holder recognition</h2>
        <p class="subtitle">Removing the need for manual dose selection.</p>
    </div>
    <div class="row">
        <h2 class="title">Electronic adjustment of burrs positioning</h2>
        <p class="subtitle">Directly adjustable from both the touch display and regulation knob.</p>
    </div>
    <div class="row">
        <h2 class="title">Integrated IoT connectivity</h2>
        <p class="subtitle">With specific apps dedicated to roasters and users, ensuring constant grinder monitoring and performance measurement.</p>
    </div>
    <div class="row">
        <h2 class="title">Cool grinder</h2>
        <p class="subtitle">Temperature monitoring of the grinding chamber combined with the forced cooling system grants consistent performance over time.</p>
    </div>
    <div class="row">
        <h2 class="title">Silent Technology</h2>
        <p class="subtitle">Reducing the grinding noise by over 20 dB compared to comparable grinders.</p>
    </div>
    <div class="row">
        <h2 class="title">"High Speed" grind dispersion</h2>
        <p class="subtitle">Special engine-burrs set optimises the dispensing speed while preserving the optimum temperature of freshly ground coffee.</p>
    </div>
    <div class="row">
        <h2 class="title">"High Speed" maintenance of burrs</h2>
        <p class="subtitle">(Without losing the grinding setting).</p>
    </div>
    <div class="row">
        <h2 class="title">All-purpose fork for "Hands-Free" operation</h2>
        <p class="subtitle">Adjustable in height and compatible with any type of filter holder (including naked).</p>
    </div>
    <div class="row">
        <h2 class="title">Bean hopper security system</h2>
    </div>
    <div class="row">
        <h2 class="title">Diamond inside burrs</h2>
        <p class="subtitle">Guarantees a superior wear resistance and duration, and preserves optimal burrs sharpness for longer than any other burr material.</p>
    </div>
</div>