<div class="row section section-2">
    <div class="row">
        <h2 class="title">BASIC INFORMATION</h2>
        <p class="subtitle"><strong>Type:</strong> On-Demand</p>
        <p class="subtitle"><strong>Hopper Size (kg):</strong> 1.2</p>
        <p class="subtitle"><strong>Colours:</strong> Black | Silver</p>
    </div>
    <div class="row">
        <h2 class="title">BURRS</h2>
        <p class="subtitle"><strong>Type:</strong> Flat</p>
        <p class="subtitle"><strong>Diameter (mm):</strong> 85</p>
        <p class="subtitle"><strong>Material:</strong> Diamond Inside</p>
    </div>
    <div class="row">
        <h2 class="title">OUTPUT</h2>
        <p class="subtitle"><strong>Daily (kg):</strong> 20</p>
        <p class="subtitle"><strong>Per second (g):</strong> 7.5 - 11</p>
        <p class="subtitle"><strong>Material:</strong> Diamond Inside</p>
    </div>
    <div class="row">
        <h2 class="title">DISPENSING SYSTEM</h2>
        <p class="subtitle"><strong>Display:</strong> Yes - Touch</p>
        <p class="subtitle"><strong>Dose Counter:</strong> Yes</p>
    </div>
    <div class="row">
        <h2 class="title">ENGINE</h2>
        <p class="subtitle"><strong>Traction:</strong> Direct</p>
        <p class="subtitle"><strong>RPM:</strong> 1420</p>
        <p class="subtitle"><strong>Power (w):</strong> 800</p>
    </div>
    <div class="row">
        <h2 class="title">DIMENSIONS</h2>
        <p class="subtitle"><strong>Height (mm):</strong> 570</p>
        <p class="subtitle"><strong>Width (mm):</strong> 230</p>
        <p class="subtitle"><strong>Depth (mm):</strong> 240</p>
        <p class="subtitle"><strong>Weight (kg):</strong> 18</p>
    </div>
</div>