<div class="page-main banner-wrapper wrapper">
    <div class="row grid-2 banner_inner">
        <div class="col-lg-12 col content-wrapper">
            <div class="row title">
                <h1>EUREKA ORO PROMETHEUS</h1>
            </div>
            <div class="row content">
                <p>An unparalleled grinder for the busiest commercial venues and baristas who demand only the best, offering up to 20KG daily output, plus a multitude of excellent features.</p>
            </div>
            <div class="row link">
                <p>To enquire contact <a class="email" href="#">LeeK@jesuk.co.uk</a> or click below.</p>
            </div>
            <div class="actions">
                <a class="btn btn-orange">ENQUIRE NOW</a>
                <a href="#info" class="btn btn-white">LEARN MORE</a>
            </div>
        </div>
        <div class="col-lg-12 col image-wrapper">
            <img src="<?= $this->getViewFileUrl('images/items.png'); ?>">
        </div>
    </div>
</div>