<?= $this->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('extra-block')
    ->toHtml(); ?>
<div id="component" class="col-md-6" data-bind="scope: 'componentBlock'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
</div>


<script type="text/x-magento-init">
    {
        "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "componentBlock": {
                    "component": "Coffeemug_ModuleExample/js/component",
                    "template": "Coffeemug_ModuleExample/component"
                }
            }
        }
    }
    }
</script>