<div data-bind="scope: 'mycomponent'">
    <div data-bind='text: content'></div>
</div>
<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app": {
                "components":{
                    "mycomponent":{
                        "content":"This is a override content",
                        "component": "js/component"
                    }
                }
            }
        }
    }
</script>