<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue) : ?>
    <div class="product attribute <?= $_className ?>" style="background: red">
        <?php if ($_attributeLabel != 'none') : ?><strong class="type"><?= $_attributeLabel ?></strong><?php endif; ?>
        <div class="value" <?= $_attributeAddAttribute ?> style="color:black">
            <?php echo $_helper->productAttribute($_product, $_product->getDescription(), 'description'); ?>
        </div>
    </div>


<?php endif; ?>